unique_name: V_BL_SECURITY
object_type: dataset
label: V_BL_SECURITY
columns:
  - name: SECURITY_ID
    data_type: string
  - name: ALADDIN_SECURITY_CUSIP
    data_type: string
  - name: ALADDIN_ISSUER_ID
    data_type: string
  - name: ALADDIN_SECURITY_GROUP
    data_type: string
  - name: ISSUE_COUNTRY
    data_type: string
  - name: RLAM_CLASSIFICATION_L1_NAME
    data_type: string
  - name: TARGET_ENUMERATION_VALUE
    data_type: string
  - name: REGION
    data_type: string
connection_id: con_SE_DEMO_LIBRARY_RLAM_POV
sql: >-

  WITH POS AS
  (
  SELECT
  SECURITY_ID

  FROM SE_DEMO_LIBRARY.RLAM_POV.SECURITY_POSITION
  GROUP BY SECURITY_ID
  ),


  SEC AS
  (
  SELECT 
  SECURITY_ID,
  ALADDIN_SECURITY_CUSIP,
  ALADDIN_SECURITY_GROUP,
  ALADDIN_ISSUER_ID,
  ISSUE_COUNTRY
       
  FROM SE_DEMO_LIBRARY.RLAM_POV.V_BL_SECURITY
  ),

  CLASS AS
  (
  SELECT
  SECURITY_ID,
  RLAM_CLASSIFICATION_L1_NAME            
  
  FROM SE_DEMO_LIBRARY.RLAM_POV.V_SECURITY_RLAM_CLASSIFICATION
  WHERE ( SECURITY_SOURCE = 'HSBC' OR SECURITY_SOURCE = 'STATESTREET' )
  GROUP BY SECURITY_ID, RLAM_CLASSIFICATION_L1_NAME
  ),

  ENUMREGION AS
  (
  SELECT
  SOURCE_ENUMERATION_VALUE,
  TARGET_ENUMERATION_VALUE
  
  FROM   SE_DEMO_LIBRARY.RLAM_POV.V_REF_ENUMERATION_MAPPING
  WHERE SOURCE_ENUMERATION_TYPE = 'ALADDIN_COUNTRY'
  AND TARGET_ENUMERATION_TYPE = 'MERCER_REGION'
  )
    
  SELECT
  POS.SECURITY_ID,
  RLAM_CLASSIFICATION_L1_NAME,
  ALADDIN_SECURITY_CUSIP,
  ALADDIN_SECURITY_GROUP,
  ALADDIN_ISSUER_ID,
  ISSUE_COUNTRY,
  TARGET_ENUMERATION_VALUE,
  CASE WHEN COALESCE(RLAM_CLASSIFICATION_L1_NAME,'UNKNOWN') NOT IN ('Cash',
  'Currency') THEN IFNULL(enumRegion.target_enumeration_value, 'UNCLASSIFIED') ELSE 'Cash'
  END AS REGION

  FROM POS

  LEFT JOIN CLASS
  ON CLASS.SECURITY_ID = POS.SECURITY_ID

  LEFT JOIN SEC
  ON SEC.SECURITY_ID = POS.SECURITY_ID

  LEFT JOIN ENUMREGION
  ON SEC.ISSUE_COUNTRY = ENUMREGION.SOURCE_ENUMERATION_VALUE
